// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REST.Data;

namespace REST.Migrations
{
    [DbContext(typeof(FlashcardsContext))]
    [Migration("20210312115627_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("REST.Model.Card", b =>
                {
                    b.Property<int>("CardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DeckOfCardsID1")
                        .HasColumnType("int");

                    b.Property<string>("TextBack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextFront")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardID");

                    b.HasIndex("DeckOfCardsID1");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("REST.Model.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DeckOfCardsID1")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID1")
                        .HasColumnType("int");

                    b.HasKey("CommentID");

                    b.HasIndex("DeckOfCardsID1");

                    b.HasIndex("UserID1");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("REST.Model.DeckOfCards", b =>
                {
                    b.Property<int>("DeckOfCardsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubjectID1")
                        .HasColumnType("int");

                    b.Property<int?>("UserID1")
                        .HasColumnType("int");

                    b.HasKey("DeckOfCardsID");

                    b.HasIndex("SubjectID1");

                    b.HasIndex("UserID1");

                    b.ToTable("DecksOfCards");
                });

            modelBuilder.Entity("REST.Model.Like", b =>
                {
                    b.Property<int>("LikeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DeckOfCardsID1")
                        .HasColumnType("int");

                    b.Property<int?>("UserID1")
                        .HasColumnType("int");

                    b.HasKey("LikeID");

                    b.HasIndex("DeckOfCardsID1");

                    b.HasIndex("UserID1");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("REST.Model.SubComment", b =>
                {
                    b.Property<int>("SubCommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CommentID1")
                        .HasColumnType("int");

                    b.Property<int?>("SubCommentedByIDUserID")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubCommentID");

                    b.HasIndex("CommentID1");

                    b.HasIndex("SubCommentedByIDUserID");

                    b.ToTable("SubComments");
                });

            modelBuilder.Entity("REST.Model.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("SubjectID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("REST.Model.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("REST.Model.Card", b =>
                {
                    b.HasOne("REST.Model.DeckOfCards", "DeckOfCardsID")
                        .WithMany("Cards")
                        .HasForeignKey("DeckOfCardsID1");

                    b.Navigation("DeckOfCardsID");
                });

            modelBuilder.Entity("REST.Model.Comment", b =>
                {
                    b.HasOne("REST.Model.DeckOfCards", "DeckOfCardsID")
                        .WithMany("Comments")
                        .HasForeignKey("DeckOfCardsID1");

                    b.HasOne("REST.Model.User", "UserID")
                        .WithMany("Comments")
                        .HasForeignKey("UserID1");

                    b.Navigation("DeckOfCardsID");

                    b.Navigation("UserID");
                });

            modelBuilder.Entity("REST.Model.DeckOfCards", b =>
                {
                    b.HasOne("REST.Model.Subject", "SubjectID")
                        .WithMany()
                        .HasForeignKey("SubjectID1");

                    b.HasOne("REST.Model.User", "UserID")
                        .WithMany()
                        .HasForeignKey("UserID1");

                    b.Navigation("SubjectID");

                    b.Navigation("UserID");
                });

            modelBuilder.Entity("REST.Model.Like", b =>
                {
                    b.HasOne("REST.Model.DeckOfCards", "DeckOfCardsID")
                        .WithMany("Likes")
                        .HasForeignKey("DeckOfCardsID1");

                    b.HasOne("REST.Model.User", "UserID")
                        .WithMany("Likes")
                        .HasForeignKey("UserID1");

                    b.Navigation("DeckOfCardsID");

                    b.Navigation("UserID");
                });

            modelBuilder.Entity("REST.Model.SubComment", b =>
                {
                    b.HasOne("REST.Model.Comment", "CommentID")
                        .WithMany("SubComments")
                        .HasForeignKey("CommentID1");

                    b.HasOne("REST.Model.User", "SubCommentedByID")
                        .WithMany("SubComments")
                        .HasForeignKey("SubCommentedByIDUserID");

                    b.Navigation("CommentID");

                    b.Navigation("SubCommentedByID");
                });

            modelBuilder.Entity("REST.Model.Comment", b =>
                {
                    b.Navigation("SubComments");
                });

            modelBuilder.Entity("REST.Model.DeckOfCards", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("REST.Model.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("SubComments");
                });
#pragma warning restore 612, 618
        }
    }
}
